// <auto-generated />
using System;
using BlazorStudents.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorStudents.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217181132_Stu")]
    partial class Stu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BlazorStudents.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BlazorStudents.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(1998, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Max",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(2001, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ann",
                            Gender = "Female",
                            LastName = "Fay",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(1995, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            Gender = "Male",
                            LastName = "Sun",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateTime(1997, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sue",
                            Gender = "Female",
                            LastName = "Fox",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 5,
                            DateOfBirth = new DateTime(1999, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ben",
                            Gender = "Male",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 6,
                            DateOfBirth = new DateTime(2002, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zoe",
                            Gender = "Female",
                            LastName = "Cox",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 7,
                            DateOfBirth = new DateTime(2000, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sam",
                            Gender = "Male",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 8,
                            DateOfBirth = new DateTime(1994, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dan",
                            Gender = "Male",
                            LastName = "Ash",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 9,
                            DateOfBirth = new DateTime(1996, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pat",
                            Gender = "Female",
                            LastName = "Lee",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 10,
                            DateOfBirth = new DateTime(1993, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kim",
                            Gender = "Female",
                            LastName = "Day",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 11,
                            DateOfBirth = new DateTime(1999, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tim",
                            Gender = "Male",
                            LastName = "Rex",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 12,
                            DateOfBirth = new DateTime(2000, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rob",
                            Gender = "Male",
                            LastName = "Ram",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 13,
                            DateOfBirth = new DateTime(1995, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jan",
                            Gender = "Female",
                            LastName = "Fry",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 14,
                            DateOfBirth = new DateTime(1998, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jim",
                            Gender = "Male",
                            LastName = "Tex",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 15,
                            DateOfBirth = new DateTime(1997, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ben",
                            Gender = "Male",
                            LastName = "Kid",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 16,
                            DateOfBirth = new DateTime(2001, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mia",
                            Gender = "Female",
                            LastName = "Chu",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 17,
                            DateOfBirth = new DateTime(1996, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ted",
                            Gender = "Male",
                            LastName = "Tao",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 18,
                            DateOfBirth = new DateTime(1994, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amy",
                            Gender = "Female",
                            LastName = "Day",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 19,
                            DateOfBirth = new DateTime(1995, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ian",
                            Gender = "Male",
                            LastName = "Roy",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 20,
                            DateOfBirth = new DateTime(2002, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liz",
                            Gender = "Female",
                            LastName = "Kit",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 21,
                            DateOfBirth = new DateTime(1997, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mat",
                            Gender = "Male",
                            LastName = "Tan",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 22,
                            DateOfBirth = new DateTime(1996, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Deb",
                            Gender = "Female",
                            LastName = "Roy",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 23,
                            DateOfBirth = new DateTime(1998, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ana",
                            Gender = "Female",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 24,
                            DateOfBirth = new DateTime(1995, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lyn",
                            Gender = "Female",
                            LastName = "Poe",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 25,
                            DateOfBirth = new DateTime(2000, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amy",
                            Gender = "Female",
                            LastName = "Raj",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 26,
                            DateOfBirth = new DateTime(1999, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kim",
                            Gender = "Female",
                            LastName = "Ash",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 27,
                            DateOfBirth = new DateTime(2001, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bec",
                            Gender = "Female",
                            LastName = "Kid",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 28,
                            DateOfBirth = new DateTime(1997, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eva",
                            Gender = "Female",
                            LastName = "Fry",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 29,
                            DateOfBirth = new DateTime(1996, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eli",
                            Gender = "Male",
                            LastName = "Lap",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 30,
                            DateOfBirth = new DateTime(2001, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sam",
                            Gender = "Male",
                            LastName = "Yim",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 31,
                            DateOfBirth = new DateTime(1997, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            Gender = "Male",
                            LastName = "Hui",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 32,
                            DateOfBirth = new DateTime(1998, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liz",
                            Gender = "Female",
                            LastName = "Jin",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 33,
                            DateOfBirth = new DateTime(1996, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ric",
                            Gender = "Male",
                            LastName = "Kuo",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 34,
                            DateOfBirth = new DateTime(1999, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pam",
                            Gender = "Female",
                            LastName = "Mak",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 35,
                            DateOfBirth = new DateTime(1994, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cat",
                            Gender = "Female",
                            LastName = "Yao",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = 36,
                            DateOfBirth = new DateTime(1995, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lou",
                            Gender = "Male",
                            LastName = "Zhu",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 37,
                            DateOfBirth = new DateTime(2000, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Dag",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 38,
                            DateOfBirth = new DateTime(1996, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Stu",
                            Gender = "Male",
                            LastName = "Day",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 39,
                            DateOfBirth = new DateTime(1998, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Gad",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 40,
                            DateOfBirth = new DateTime(1997, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            Gender = "Male",
                            LastName = "Bee",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 41,
                            DateOfBirth = new DateTime(1995, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jim",
                            Gender = "Male",
                            LastName = "Ots",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 42,
                            DateOfBirth = new DateTime(2001, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Mag",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 43,
                            DateOfBirth = new DateTime(1999, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hal",
                            Gender = "Male",
                            LastName = "Doe",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 44,
                            DateOfBirth = new DateTime(2002, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Roy",
                            Gender = "Male",
                            LastName = "Kim",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 45,
                            DateOfBirth = new DateTime(1993, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Vis",
                            Gender = "Male",
                            LastName = "Cox",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 46,
                            DateOfBirth = new DateTime(1994, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kay",
                            Gender = "Female",
                            LastName = "Aga",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 47,
                            DateOfBirth = new DateTime(1995, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Reo",
                            Gender = "Male",
                            LastName = "Hui",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 48,
                            DateOfBirth = new DateTime(2001, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            Gender = "Male",
                            LastName = "Roe",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 49,
                            DateOfBirth = new DateTime(1996, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jay",
                            Gender = "Male",
                            LastName = "Eff",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 50,
                            DateOfBirth = new DateTime(1997, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eva",
                            Gender = "Female",
                            LastName = "Chu",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 51,
                            DateOfBirth = new DateTime(1997, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lex",
                            Gender = "Male",
                            LastName = "Rae",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 52,
                            DateOfBirth = new DateTime(1995, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lin",
                            Gender = "Female",
                            LastName = "Dex",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 53,
                            DateOfBirth = new DateTime(1998, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liz",
                            Gender = "Female",
                            LastName = "Dag",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 54,
                            DateOfBirth = new DateTime(1999, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ben",
                            Gender = "Male",
                            LastName = "Shy",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 55,
                            DateOfBirth = new DateTime(2000, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rob",
                            Gender = "Male",
                            LastName = "Bos",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 56,
                            DateOfBirth = new DateTime(1996, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            Gender = "Female",
                            LastName = "Mac",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 57,
                            DateOfBirth = new DateTime(1994, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edi",
                            Gender = "Male",
                            LastName = "Gee",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 58,
                            DateOfBirth = new DateTime(1997, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eva",
                            Gender = "Female",
                            LastName = "Cao",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 59,
                            DateOfBirth = new DateTime(1995, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jun",
                            Gender = "Male",
                            LastName = "Lam",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 60,
                            DateOfBirth = new DateTime(2001, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eli",
                            Gender = "Male",
                            LastName = "Tao",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 61,
                            DateOfBirth = new DateTime(1998, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ana",
                            Gender = "Female",
                            LastName = "Bay",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 62,
                            DateOfBirth = new DateTime(1996, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gil",
                            Gender = "Male",
                            LastName = "Tal",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 63,
                            DateOfBirth = new DateTime(1999, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Wes",
                            Gender = "Male",
                            LastName = "Dey",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 64,
                            DateOfBirth = new DateTime(2000, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nea",
                            Gender = "Female",
                            LastName = "Tan",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 65,
                            DateOfBirth = new DateTime(1994, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ava",
                            Gender = "Female",
                            LastName = "Day",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 66,
                            DateOfBirth = new DateTime(1998, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rie",
                            Gender = "Female",
                            LastName = "Ray",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 67,
                            DateOfBirth = new DateTime(1995, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ken",
                            Gender = "Male",
                            LastName = "Sim",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 68,
                            DateOfBirth = new DateTime(1997, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liz",
                            Gender = "Female",
                            LastName = "Kim",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 69,
                            DateOfBirth = new DateTime(1996, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Max",
                            Gender = "Male",
                            LastName = "Fur",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 70,
                            DateOfBirth = new DateTime(2001, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Edi",
                            Gender = "Male",
                            LastName = "Kai",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 71,
                            DateOfBirth = new DateTime(1999, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            Gender = "Male",
                            LastName = "Sha",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 72,
                            DateOfBirth = new DateTime(1997, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gem",
                            Gender = "Female",
                            LastName = "Lin",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 73,
                            DateOfBirth = new DateTime(1995, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ama",
                            Gender = "Female",
                            LastName = "Kam",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 74,
                            DateOfBirth = new DateTime(1998, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zac",
                            Gender = "Male",
                            LastName = "Der",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 75,
                            DateOfBirth = new DateTime(2000, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liz",
                            Gender = "Female",
                            LastName = "Car",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 76,
                            DateOfBirth = new DateTime(1996, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kit",
                            Gender = "Male",
                            LastName = "Ngo",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 77,
                            DateOfBirth = new DateTime(1997, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tom",
                            Gender = "Male",
                            LastName = "Ren",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 78,
                            DateOfBirth = new DateTime(1994, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kal",
                            Gender = "Male",
                            LastName = "Hon",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 79,
                            DateOfBirth = new DateTime(2002, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Avi",
                            Gender = "Male",
                            LastName = "Gil",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 80,
                            DateOfBirth = new DateTime(1995, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ada",
                            Gender = "Female",
                            LastName = "Dao",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 81,
                            DateOfBirth = new DateTime(1999, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eva",
                            Gender = "Female",
                            LastName = "Kim",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 82,
                            DateOfBirth = new DateTime(1997, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Amy",
                            Gender = "Female",
                            LastName = "Kam",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 83,
                            DateOfBirth = new DateTime(1996, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Noa",
                            Gender = "Male",
                            LastName = "Sim",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 84,
                            DateOfBirth = new DateTime(1998, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ben",
                            Gender = "Male",
                            LastName = "Kai",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 85,
                            DateOfBirth = new DateTime(2000, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mae",
                            Gender = "Female",
                            LastName = "Car",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 86,
                            DateOfBirth = new DateTime(1994, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mae",
                            Gender = "Female",
                            LastName = "Der",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 87,
                            DateOfBirth = new DateTime(2001, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lee",
                            Gender = "Male",
                            LastName = "Hon",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 88,
                            DateOfBirth = new DateTime(1997, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Gus",
                            Gender = "Male",
                            LastName = "Lin",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 89,
                            DateOfBirth = new DateTime(1995, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ava",
                            Gender = "Female",
                            LastName = "Bay",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 90,
                            DateOfBirth = new DateTime(2002, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ari",
                            Gender = "Male",
                            LastName = "Sim",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 91,
                            DateOfBirth = new DateTime(1996, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kai",
                            Gender = "Male",
                            LastName = "Lee",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 92,
                            DateOfBirth = new DateTime(1999, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            Gender = "Female",
                            LastName = "Doe",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 93,
                            DateOfBirth = new DateTime(1994, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivy",
                            Gender = "Female",
                            LastName = "Kim",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 94,
                            DateOfBirth = new DateTime(1998, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mia",
                            Gender = "Female",
                            LastName = "Sun",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 95,
                            DateOfBirth = new DateTime(1996, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lia",
                            Gender = "Female",
                            LastName = "Fox",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 96,
                            DateOfBirth = new DateTime(1997, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ian",
                            Gender = "Male",
                            LastName = "Day",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 97,
                            DateOfBirth = new DateTime(1999, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bra",
                            Gender = "Male",
                            LastName = "Tan",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 98,
                            DateOfBirth = new DateTime(2001, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eli",
                            Gender = "Male",
                            LastName = "Chu",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 99,
                            DateOfBirth = new DateTime(1995, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Max",
                            Gender = "Male",
                            LastName = "Cox",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 100,
                            DateOfBirth = new DateTime(1994, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ann",
                            Gender = "Female",
                            LastName = "Kuo",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 101,
                            DateOfBirth = new DateTime(1996, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liv",
                            Gender = "Female",
                            LastName = "Kim",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 102,
                            DateOfBirth = new DateTime(1998, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jay",
                            Gender = "Male",
                            LastName = "Tan",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = 103,
                            DateOfBirth = new DateTime(1999, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ace",
                            Gender = "Male",
                            LastName = "Sun",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 104,
                            DateOfBirth = new DateTime(2002, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kit",
                            Gender = "Male",
                            LastName = "Doe",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 105,
                            DateOfBirth = new DateTime(1995, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kim",
                            Gender = "Female",
                            LastName = "Kay",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 106,
                            DateOfBirth = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lyn",
                            Gender = "Female",
                            LastName = "Bar",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 107,
                            DateOfBirth = new DateTime(1996, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tae",
                            Gender = "Male",
                            LastName = "Sae",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 108,
                            DateOfBirth = new DateTime(1998, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pri",
                            Gender = "Female",
                            LastName = "Day",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 109,
                            DateOfBirth = new DateTime(1989, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Naz",
                            Gender = "Female",
                            LastName = "Rai",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = 110,
                            DateOfBirth = new DateTime(1999, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jan",
                            Gender = "Female",
                            LastName = "Ojo",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = 111,
                            DateOfBirth = new DateTime(2002, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mac",
                            Gender = "Male",
                            LastName = "Mah",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = 112,
                            DateOfBirth = new DateTime(2004, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tim",
                            Gender = "Male",
                            LastName = "Maw",
                            School = "Nursing"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("BLOB");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlazorStudents.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlazorStudents.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("BlazorStudents.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<uint>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1.ToJson("Data");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorStudents.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlazorStudents.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
