// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sports.Data;

#nullable disable

namespace Sports.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Sports.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamName");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FirstName = "Sven",
                            LastName = "Baertschi",
                            Position = "Forward",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 2,
                            FirstName = "Hendrik",
                            LastName = "Sedin",
                            Position = "Left Wing",
                            TeamName = "Canucks"
                        },
                        new
                        {
                            PlayerId = 3,
                            FirstName = "John",
                            LastName = "Rooster",
                            Position = "Right Wing",
                            TeamName = "Flames"
                        },
                        new
                        {
                            PlayerId = 4,
                            FirstName = "Bob",
                            LastName = "Plumber",
                            Position = "Defense",
                            TeamName = "Oilers"
                        });
                });

            modelBuilder.Entity("Sports.Models.Team", b =>
                {
                    b.Property<string>("TeamName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamName");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamName = "Canucks",
                            City = "Vancouver"
                        },
                        new
                        {
                            TeamName = "Sharks",
                            City = "San Jose"
                        },
                        new
                        {
                            TeamName = "Oilers",
                            City = "Edmonton"
                        },
                        new
                        {
                            TeamName = "Flames",
                            City = "Calgary"
                        },
                        new
                        {
                            TeamName = "Leafs",
                            City = "Toronto"
                        },
                        new
                        {
                            TeamName = "Ducks",
                            City = "Anaheim"
                        },
                        new
                        {
                            TeamName = "Lightening",
                            City = "Tampa Bay"
                        },
                        new
                        {
                            TeamName = "Blackhawks",
                            City = "Chicago"
                        });
                });

            modelBuilder.Entity("Sports.Models.Player", b =>
                {
                    b.HasOne("Sports.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Sports.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
