@StudentsMinimalApi_HostAddress = http://localhost:5293

GET {{StudentsMinimalApi_HostAddress}}/api/students
Accept: application/json

###

GET {{StudentsMinimalApi_HostAddress}}/api/students/school/Medicine
Accept: application/json

###

GET {{StudentsMinimalApi_HostAddress}}/api/students/111
Accept: application/json

###

POST {{StudentsMinimalApi_HostAddress}}/api/students
Content-Type: application/json

{
    "firstName": "Joy",
    "lastName": "Sim",
    "school": "Mining"
}

###

PUT {{StudentsMinimalApi_HostAddress}}/api/students/111
Content-Type: application/json

{
    "firstName": "Tom",
    "lastName": "Hay",
    "school": "Computing"
}

###

DELETE {{StudentsMinimalApi_HostAddress}}/api/students/111
###